### PR TITLE
Update pipeline.py

### PR DESCRIPTION
**Pull request by bhavya2021245**
**1. Efficient CPU-bound Task Handling:**

**Improvement:** I introduced a ThreadPoolExecutor to handle CPU-bound tasks in a separate thread pool. This ensures non-blocking execution by offloading those tasks to a separate pool, allowing the event loop to remain responsive.
**Implementation:** For CPU-bound functions like summarize_texts, extract_keywords, and analyze_sentiments, I wrapped them in async functions that use loop.run_in_executor(None, function). This runs them in a thread pool, ensuring the event loop is not blocked.

**2. Robust Error Handling with Retries:**

**Improvement:** I implemented a retry mechanism using the Tenacity library, which retries the HTTP requests and CPU-bound tasks in case of failures due to network or transient errors. This makes the system more resilient to failures.
**Implementation:** I wrapped HTTP requests (like fetch_article_content) and CPU-bound tasks in a retry mechanism. This retry logic is defined using a retry_decorator that will attempt the function up to 5 times with an exponential backoff.

**3. Efficient Database Insertion with Batching:**

**Improvement:** I added a batching mechanism for database insertions. Updates are now queued and written to the database in bulk, reducing the frequency of database operations and improving overall performance.
**Implementation:** I created a coroutine (db_writer) that monitors a queue (db_queue) and inserts queued updates into the database in batches. This queueing mechanism reduces the number of individual database write operations, thereby improving latency and performance.

### CODE REVIEW

**Comment by Devasy23** [comment]
Hi @bhavya2021245 ,

Thanks for your contribution! I've gone through the changes, and here's my detailed feedback:

1. Efficient CPU-bound Task Handling:
I like the introduction of the ThreadPoolExecutor for managing CPU-bound tasks. It’s a great way to maintain responsiveness while handling tasks like summarization, keyword extraction, and sentiment analysis. This approach aligns well with our async model, so no concerns here.


2. Robust Error Handling with Retries:
The retry mechanism using Tenacity works well for transient network errors. However, for tasks involving the Gemini API (like summarize_text), retries may not be the best fit due to the 10 requests/minute limit. Instead, we could manage this with a token bucket or token rotator to avoid exceeding rate limits. Another critical point: tasks like summarization should only run if the content was successfully fetched. Some websites block scraping, so in those cases, we should ensure the rest of the pipeline doesn’t run unnecessarily.


3. Efficient Database Insertion with Batching:
The batching mechanism for database insertions is a solid addition. Queuing the updates and inserting them in bulk will certainly help reduce the load on the database and improve performance. However, since we’re using MongoDB, we can switch to Motor for fully async operations, which will fit seamlessly into the rest of the pipeline.



That said, one key enhancement I’ve been considering is to implement a Pipeline Manager class. This class will tightly manage all pipeline tasks and handle cases where any step in the process (like content fetching) fails. For instance, if content isn’t fetched, the rest of the steps—summarization, keyword extraction, sentiment analysis—shouldn't proceed, and the article will be marked as "failed." We can also remove any incomplete fields (except ID and URL) to ensure we’re not wasting resources processing or reprocessing incomplete data.

With the Pipeline Manager, we could further improve robustness and streamline error handling, making it easier to track articles that failed at any stage. This way, we ensure the integrity of the data, and avoid unnecessary retries.

Let me know your thoughts on this idea. Overall, your changes are great and bring significant improvements!

**Comment by bhavya2021245** [comment]
**Your ideas for further improving the pipeline are excellent and thoughtful. Here's a breakdown of my thoughts on each aspect**

**API Rate Limits (Token Bucket/Rotator):** Great idea! Instead of using retries, a token bucket or rotator for APIs like Gemini ensures you stay within rate limits. This is a much better solution for managing API requests efficiently.

**Skipping Unnecessary Tasks:** Excellent suggestion. If content fetching fails, subsequent steps (summarization, sentiment analysis) should be skipped to save resources. This will prevent processing incomplete data and improve efficiency.

**Switching to Motor for Async DB Operations:** A smart move! Motor is fully asynchronous and will improve performance by seamlessly integrating MongoDB operations with the rest of your async pipeline.

**Pipeline Manager Class:** This is a fantastic way to centralize task management, handle errors, and track progress. It will ensure failed articles don’t continue through the pipeline and help maintain data integrity.

**Comment by bhavya2021245** [comment]
I have made the changes also
Kindly review it.

**Comment by Devasy23** [comment]
> I have made the changes also Kindly review it.

Wow, that was fast! Are your changes ready to be tested without doing anything?

**Comment by Devasy23** [comment]
Hey @bhavya2021245, great progress on the implementation! I noticed a couple of things that still need to be addressed:

1. **Token Bucket Class**: The `token_bucket` class still needs to be added. You can raise a separate PR for that if you prefer.
2. **Pipeline Manager Class**: Consider making the Pipeline Manager class more modular, so it can be easily reused and extended for other pipeline steps in the future.

Let me know if you need any help with these!

**Comment by bhavya2021245** [comment]
I have incorporated these changes in the new code.

**Comment by Devasy23** [comment]
@bhavya2021245 I've reviewed your changes but you still need to implement several functions for this code to work. like `fetch_article_content_retry`, `summarize_texts_retry`, etc..


So the correct approach for implementing this would be to divide changes into 2 or 3 separate working PRs and then merge them all. In this way, it would benefit you from a GSSOC perspective, benefit us from the ease of reviewing and testing purposes, and help you focus on one thing at a time.

**Comment by Devasy23** [comment]
Sorry this was accidentally committed into main

**Pull request merged**
