### PR TITLE
Main

### PR DESCRIPTION
**Pull request by snehas-05**
Title: Add Personalized News Mood Board Feature and User Preferences

Description: This pull request introduces the Personalized News Mood Board feature, allowing users to filter news articles based on their emotional tones (happy, sad, angry, surprised). It also implements user preferences functionality, enabling users to save and retrieve their preferred emotional tones securely. New API endpoints have been added for saving user preferences and fetching news based on selected emotions. Database migrations have been created to support the new models.
For better understanding of the code, I have made a separate folder named as personalised_news
I request you to kindly merge it to enhance your website/project and also to enhance user experience.

### CODE REVIEW

**Comment by Devasy23** [comment]
Hi @snehas-05 , please include ss of your changes and working demo if possible

**Comment by snehas-05** [comment]
Hey I would love to add a screenshot of my output but I tried running code on my pc. My code is correct but it is not running as I need to install a lot of components. I would appreciate it if you run my code on your own as you are a trained in this field and I am just a beginner

**Comment by Devasy23** [comment]
@snehas-05 how to run it, as you haven't committed all of the changes.

And please don't use Django, use fast API, as this is a very small project to complicate with django

**Comment by snehas-05** [comment]
Ok so should I make changes according to fast API and make a new pr?

**Comment by Devasy23** [comment]
Yes, you can make a separate pr or maybe change in this one, whatever suits you

**Comment by snehas-05** [comment]
For sure

**Comment by snehas-05** [comment]
Hey I have made all the changes required. Now do I need to create a new pr? If yes how? Because I tried creating a new pr but I'm not able to create
Although the changes are made, you can go through the changes and let me know if they are not made.
And tell me about pr also

**Comment by vrajpatelll** [comment]
Hi @snehas-05,
Thank you for your efforts! However, the changes in this PR don't align with the project's needs and it's quite messy for merging. If you're interested in contributing, I’d be more than happy but you need to create a new PR with relevant changes, including a clear title and description. I'm closing this PR.
Thank you!

**Pull request closed without merging**
