### PR TITLE
Create auto-comment-issue.yml

### PR DESCRIPTION
**Pull request by sejals23**
Created auto comment file
Issue Fixes # 60

### CODE REVIEW

**Comment by Devasy23** [comment]
As it is running on issues opened can you integrate your code into auto assign workflow

**Comment by sejals23** [comment]
@Devasy23 Should I enclose this pr and raise a new pr

**Comment by Devasy23** [comment]
Not necessarily

**Comment by Devasy23** [comment]
Not necessarily

**Comment by sejals23** [comment]
@Devasy23 Sir i have updated it....Please have a look

**Comment by Devasy23** [comment]
Please do it raise a dummy issue for testing of this workflow, and remove the other file as it's no longer required

**Comment by Devasy23** [comment]
What happened?

**Comment by sejals23** [comment]
@Devasy23 Sir actually I am facing some problem so that's why I wanna to raise new pr

**Comment by Devasy23** [comment]
> @Devasy23 Sir actually I am facing some problem so that's why I wanna to raise new pr
No issues, if you need any help you can reach out to us or the mentors will guide you

**Pull request closed without merging**
